APP_NAME = "erpnext_extended_reports"
STATISTICS_METHODNAME=""
TRIAL_BALANCE_METHODNAME="get_trial_balance"

API_PREFIX=f"{APP_NAME}.api"

TRIAL_BALANCE_APINAME=f"{API_PREFIX}.{TRIAL_BALANCE_METHODNAME}"